// 타입 옵션 정의
export const typeOptions = [
    { value: '노말',   label: '노말' },
    { value: '불꽃',   label: '불꽃' },
    { value: '물',     label: '물' },
    { value: '전기',   label: '전기' },
    { value: '풀',     label: '풀' },
    { value: '얼음',   label: '얼음' },
    { value: '격투',   label: '격투' },
    { value: '독',     label: '독' },
    { value: '땅',     label: '땅' },
    { value: '비행',   label: '비행' },
    { value: '에스퍼', label: '에스퍼' },
    { value: '벌레',   label: '벌레' },
    { value: '바위',   label: '바위' },
    { value: '고스트', label: '고스트' },
    { value: '드래곤', label: '드래곤' },
    { value: '악',     label: '악' },
    { value: '강철',   label: '강철' },
    { value: '페어리', label: '페어리' },
];