// 타입 이미지 정의
export const typeImages = {
    '풀': '/image/type/grass.png',
    '독': '/image/type/poison.png',
    '불꽃': '/image/type/fire.png',
    '비행': '/image/type/wind.png',
    '물': '/image/type/water.png',
    '벌레': '/image/type/bug.png',
    '노말': '/image/type/normal.png',
    '땅': '/image/type/earth.png',
    '얼음': '/image/type/ice.png',
    '강철': '/image/type/collins.png',
    '페어리': '/image/type/fairy.png',
    '악': '/image/type/devil.png',
    '바위': '/image/type/rock.png',
    '에스퍼': '/image/type/psychic.png',
    '격투': '/image/type/fight.png',
    '전기': '/image/type/electr.png',
    '고스트': '/image/type/ghost.png',
    '드래곤': '/image/type/dragon.png',
};